UPDATE `creature_template` SET `ScriptName`='boss_blood_queen_lanathel' WHERE (`entry`='37955');
UPDATE `creature_template` SET `ScriptName`='npc_swarming_shadows' WHERE (`entry`='38163');
UPDATE `creature_template` SET `ScriptName`='boss_saurfang' WHERE (`entry`='37813');
UPDATE `creature_template` SET `ScriptName`='npc_bloodbeast' WHERE (`entry`='38508');
UPDATE `creature_template` SET `ScriptName`='boss_Festergut' WHERE (`entry`='36626');
UPDATE `gameobject_template` SET `ScriptName` = 'icecrown_teleporter' WHERE `entry` IN (202223,202235,202242, 202243,202244,202245,202246);
UPDATE `gameobject_template` SET `flags` = 0 WHERE `entry` = 202223;
UPDATE `creature_template` SET `ScriptName`='Boss_Lady_Deathwisper' WHERE (`entry`='36855');
UPDATE `creature_template` SET `minlevel`='80',`maxlevel`='80',`faction_A`='16',`faction_H`='16',`ScriptName`='Cold_Flame' WHERE (`entry`='36672');
UPDATE `creature_template` SET `minlevel`='83',`maxlevel`='83',`faction_A`='16',`faction_H`='16',`ScriptName`='Boss_Lord_Marrowgar' WHERE (`entry`='36612');
UPDATE `creature_template` SET `minlevel`='80',`maxlevel`='80',`faction_A`='16',`faction_H`='16',`flags_extra`='2',`ScriptName`='BoneSpike' WHERE (`entry`='38711');
UPDATE `creature_template` SET `ScriptName`='Boss_ProfessorPutricide' WHERE (`entry`='36678');  
UPDATE `creature_template` SET `ScriptName`='Mob_VolatileOoze' WHERE (`entry`='37697');  
UPDATE `creature_template` SET `ScriptName`='Boss_Sindragosa' WHERE (`entry`='36853');
UPDATE `creature_template` SET `ScriptName`='boss_the_lich_king' WHERE (`entry`='36597');
UPDATE `creature_template` SET `ScriptName`='boss_tirion_icc' WHERE (`entry`='38995');
UPDATE `creature_template` SET `npcflag` = 1 WHERE `entry` = 38995;
UPDATE `creature_template` SET `ScriptName`='npc_Ice_Puls' WHERE (`entry`='36633');
UPDATE `creature_template` SET `ScriptName`='npc_Valkyr' WHERE (`entry`='36609');
UPDATE `creature_template` SET `ScriptName`='npc_Ghoul' WHERE (`entry`='37695');
UPDATE `creature_template` SET `ScriptName`='npc_Defile' WHERE (`entry`='38757');
UPDATE `creature_template` SET `ScriptName`='npc_RagingSpirit' WHERE (`entry`='36701');
UPDATE `creature_template` SET `Health_mod`='50000' WHERE (`entry`='30494');
UPDATE `creature_template` SET `vehicleId` = 318 WHERE `entry` = 36609;
UPDATE `creature_template` SET `ScriptName`='boss_Rotface' WHERE `entry`= 36627;
UPDATE `creature_template` SET `ScriptName`='npc_OozeLittle' WHERE `entry`= 36897;
UPDATE `creature_template` SET `ScriptName`='npc_OozeBig' WHERE `entry`= 36899;
UPDATE `creature_template` SET `ScriptName` = 'npc_NerubarBroodkeeper' WHERE `entry` = 36725;
UPDATE `creature_template` SET `ScriptName` = 'npc_TheDamned' WHERE `entry` = 37011;
UPDATE `creature_template` SET `ScriptName` = 'npc_ServantoftheThrone' WHERE `entry` = 36724;
UPDATE `creature_template` SET `ScriptName` = 'npc_AncientSkeletalSoldier' WHERE `entry` = 37012;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathboundWard' WHERE `entry` = 37007;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathspeakerAttedant' WHERE `entry` = 36811;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathspeakerDisciple' WHERE `entry` = 36807;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathspeakerHighPriest' WHERE `entry` = 36829;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathspeakerServant' WHERE `entry` = 36844;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathspeakerZealot' WHERE `entry` = 36808;
UPDATE `creature_template` SET `ScriptName` = 'npc_CultFanatic' WHERE `entry` = 38135;
UPDATE `creature_template` SET `ScriptName` = 'npc_CultAdherent' WHERE `entry` = 37949;
UPDATE `creature_template` SET `ScriptName` = 'boss_blood_elf_Valanar' WHERE `entry` = 37970;
UPDATE `creature_template` SET `ScriptName` = 'boss_blood_elf_Keleset' WHERE `entry` = 37972;
UPDATE `creature_template` SET `ScriptName` = 'boss_blood_elf_Taldaram' WHERE `entry` = 37973;
