UPDATE `creature_template` SET `ScriptName`='boss_blood_queen_lanathel' WHERE (`entry`='37955');
UPDATE `creature_template` SET `ScriptName`='npc_swarming_shadows' WHERE (`entry`='38163');
UPDATE `creature_template` SET `ScriptName`='boss_saurfang' WHERE (`entry`='37813');
UPDATE `creature_template` SET `ScriptName`='npc_bloodbeast' WHERE (`entry`='38508');
UPDATE `creature_template` SET `ScriptName`='boss_Festergut' WHERE (`entry`='36626');
UPDATE `gameobject_template` SET `ScriptName` = 'icecrown_teleporter' WHERE `entry` IN (202223,202235,202242, 202243,202244,202245,202246);
UPDATE `creature_template` SET `ScriptName`='Boss_Lady_Deathwisper' WHERE (`entry`='36855');
UPDATE `creature_template` SET `ScriptName`='mob_CultAdherents' WHERE (`entry`='37949');
UPDATE `creature_template` SET `ScriptName`='Boss_ProfessorPutricide' WHERE (`entry`='36678');  
UPDATE `creature_template` SET `ScriptName`='Mob_VolatileOoze' WHERE (`entry`='37697');  
UPDATE `creature_template` SET `ScriptName`='Boss_Sindragosa' WHERE (`entry`='36853');
UPDATE `creature_template` SET `ScriptName`='boss_the_lich_king' WHERE (`entry`='36597');
UPDATE `creature_template` SET `ScriptName`='boss_tirion_icc' WHERE (`entry`='38995');
UPDATE `creature_template` SET `ScriptName`='mob_Ice_Puls' WHERE (`entry`='36633');
UPDATE `creature_template` SET `ScriptName`='mob_Valkyr' WHERE (`entry`='36609');
UPDATE `creature_template` SET `ScriptName`='mob_Ghoul' WHERE (`entry`='37695');
UPDATE `creature_template` SET `ScriptName`='mob_Defile' WHERE (`entry`='38757');
UPDATE `creature_template` SET `ScriptName`='mob_RagingSpirit' WHERE (`entry`='36701');
UPDATE `creature_template` SET `ScriptName`='boss_Rotface' WHERE `entry`= 36627;
UPDATE `creature_template` SET `ScriptName`='npc_OozeLittle' WHERE `entry`= 36897;
UPDATE `creature_template` SET `ScriptName`='npc_OozeBig' WHERE `entry`= 36899;
UPDATE `creature_template` SET `ScriptName` = 'npc_NerubarBroodkeeper' WHERE `entry` = 36725;
UPDATE `creature_template` SET `ScriptName` = 'npc_TheDamned' WHERE `entry` = 37011;
UPDATE `creature_template` SET `ScriptName` = 'npc_ServantoftheThrone' WHERE `entry` = 36724;
UPDATE `creature_template` SET `ScriptName` = 'npc_AncientSkeletalSoldier' WHERE `entry` = 37012;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathboundWard' WHERE `entry` = 37007;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathspeakerAttedant' WHERE `entry` = 36811;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathspeakerDisciple' WHERE `entry` = 36807;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathspeakerHighPriest' WHERE `entry` = 36829;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathspeakerServant' WHERE `entry` = 36844;
UPDATE `creature_template` SET `ScriptName` = 'npc_DeathspeakerZealot' WHERE `entry` = 36808;
UPDATE `creature_template` SET `ScriptName` = 'npc_CultFanatic' WHERE `entry` = 38135;
UPDATE `creature_template` SET `ScriptName` = 'npc_CultAdherent' WHERE `entry` = 37949;
UPDATE `creature_template` SET `ScriptName` = 'boss_Valanar' WHERE `entry` = 37970;
UPDATE `creature_template` SET `ScriptName` = 'boss_Keleset' WHERE `entry` = 37972;
UPDATE `creature_template` SET `ScriptName` = 'boss_Taldaram' WHERE `entry` = 37973;