-- twins
UPDATE `creature_template` SET `scriptname` = 'mob_light_spell' WHERE `entry`='34568';
UPDATE `creature_template` SET `scriptname` = 'mob_black_spell' WHERE `entry`='34567';
UPDATE `creature_template` SET `scriptname` = 'npc_toc6_announcer' WHERE `entry` = '34816';
UPDATE `creature_template` SET `scriptname` = 'npc_warrior' WHERE `entry` IN (34475,34453);
UPDATE `creature_template` SET `scriptname` = 'npc_mage' WHERE `entry` IN (34468,34449);
UPDATE `creature_template` SET `scriptname` = 'npc_shaman_ench' WHERE `entry` IN (34463,34455);
UPDATE `creature_template` SET `scriptname` = 'npc_hunter' WHERE `entry` IN (34467,34448);
UPDATE `creature_template` SET `scriptname` = 'npc_rogue' WHERE `entry` IN (34472,34454);
UPDATE `creature_template` SET `scriptname` = 'npc_paladin_retro' WHERE `entry` IN (34471,34456);
UPDATE `creature_template` SET `scriptname` = 'npc_death_knight' WHERE `entry` IN (34461,34458);
UPDATE `creature_template` SET `scriptname` = 'npc_paladin_holy' WHERE `entry` IN (34465,34445);
UPDATE `creature_template` SET `scriptname` = 'npc_druid_balans' WHERE `entry` IN (34460,34451);
UPDATE `creature_template` SET `scriptname` = 'npc_druid_restor' WHERE `entry` IN (34469,34459);
UPDATE `creature_template` SET `scriptname` = 'npc_priest_disc' WHERE `entry` IN (34466,34447);
UPDATE `creature_template` SET `scriptname` = 'npc_priest_shadow' WHERE `entry` IN (34473,34441);
UPDATE `creature_template` SET `scriptname` = 'npc_warlock' WHERE `entry` IN (34474,34450);
UPDATE `creature_template` SET `scriptname` = 'boss_lord_jaraksus' WHERE `entry` = '34780';
UPDATE `creature_template` SET `scriptname` = 'boss_gormok' WHERE `entry` = '34796';
UPDATE `creature_template` SET `scriptname` = 'npc_dreadscale' WHERE `entry` = '34799';
UPDATE `creature_template` SET `scriptname` = 'npc_acidmaw' WHERE `entry` = '35144';
UPDATE `creature_template` SET `scriptname` = 'boss_icehowl' WHERE `entry` = '34797';
UPDATE `creature_template` SET `scriptname` = 'boss_anub_arak_crusader' WHERE `entry` = '34564';
UPDATE `creature_template` SET `scriptname` = 'npc_borrower' WHERE `entry` = '34607';
UPDATE `creature_template` SET `scriptname` = 'boss_fjola' WHERE `entry` = '34497';
UPDATE `creature_template` SET `scriptname` = 'boss_eydis' WHERE `entry` = '34496';
UPDATE `creature_template` SET `scriptname` = 'boss_freya' WHERE `entry` = '32906';
UPDATE `creature_template` SET `scriptname` = 'mob_detonator' WHERE `entry` = '32918';
UPDATE `creature_template` SET `scriptname` = 'mob_elder_stonebar' WHERE `entry` IN (32913,32914,32915);
UPDATE `instance_template` SET `script` = 'instance_trial_of_the_crusader' WHERE map = 649;